[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md", "--line_width", "120",  "--indent-width", "4"] }
# language-server = { command = "C:\\Users\\dorw_lo\\.cargo\\bin\\mdpls.exe" }
# config = { markdown.preview.auto = true, markdown.preview.browser = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" }


[[language]]
name = "html"
scope = "source.html"
injection-regex = "html"
file-types = ["html", "cshtml", "razor"]
comment-token = "//"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "html",  "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "c-sharp"
scope = "source.cs"
injection-regex = "c-sharp"
roots = ["sln", "csproj"]
file-types = ["cs"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dotnet format', args = ["--include", "${file}"] }
language-server = { command = "csharp-ls", timeout=10000 }
auto-format = true
# language-server = { command = "C:\\Users\\dorw_lo\\scoop\\shims\\omnisharp.exe", args = ["-lsp"], timeout=1000000 }

[[language]]
name = "latex"

[language.config.build]
executable = "latexmk"
args = ["-pdf", "-interaction=nonstopmode", "-synctex=1", "%f"]
indent = { tab-width = 4, unit = "    " }
onSave = true

[language.config.chktex]
onOpenAndSave = true
onEdit = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
roots = ["pyproject.toml"]
indent = { tab-width = 4, unit = "    " }
comment-token = "#"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true


[[language]]
name = "javascript"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js",  "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "json"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json",  "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "typescript"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts",  "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "jsx"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx",  "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "tsx"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx",  "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true