[[language]]
name = "pwsh"
scope = "source.ps1"
roots = [".git"]
file-types = ["ps1"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }

# language-servers = [ "pwsh" ]
# [language-server.pwsh]
# command = "pwsh"
# args = ["-NoLogo -NoProfile -Command '$PSES_BUNDLE_PATH/PowerShellEditorServices/Start-EditorServices.ps1 -BundledModulesPath $PSES_BUNDLE_PATH -LogPath $SESSION_TEMP_PATH/logs.log -SessionDetailsPath $SESSION_TEMP_PATH/session.json -FeatureFlags @() -AdditionalModules @() -HostName 'My Client' -HostProfileId 'myclient' -HostVersion 1.0.0 -LogLevel Normal'"]

# https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "bash"
file-types = ["sh"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "shfmt", args = ["-i", "4"] }
auto-format = true
language-servers = ["bashls"]

[language-server.bashls]
command = "bash-language-server"
args = ["start"]
language-servers = ["shellcheck", "bashls"]

[language-server.shellcheck]
command = "shellcheck"

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md", "--line-width", "120", "--indent-width", "4"] }
# language-servers = ["markdown-mdpls"]

# [language-server.markdown-mdpls]
# command = "C:\\Users\\dorw_lo\\.cargo\\bin\\mdpls.exe"
# config = { markdown.preview.auto = true, markdown.preview.browser = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" }

# Use npm i -g vscode-langservers-extracted to install the html etc. language server
[[language]]
name = "html"
scope = "source.html"
injection-regex = "html"
file-types = ["html", "cshtml", "razor"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "c-sharp"
scope = "source.cs"
injection-regex = "c-sharp"
roots = ["sln", "csproj"]
file-types = ["cs"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dotnet format', args = ["--include", "${file}"] }
auto-format = true

# [language-server.csharp-ls]
# command = "csharp-ls"
# timeout = 10000
# [language-server.omnisharp]
# command = "C:\\Users\\dorw_lo\\scoop\\shims\\\omnisharp.exe"
# args = ["-lsp"]
# timeout = 10000

# [[language]]
# name = "bibtex"
# file-types = ["bib"]
# indent = { tab-width = 4, unit = "    " }
# formatter = { command = "bibtex-tidy", args = ["--modify", "--space=4", "--no-tab", "--escape", "--strip-enclosing-braces", "--drop-all-caps", "--wrap=120", "${file}"] }
# auto-format = true
[[language]]
name = "latex"

# [language.config.texlab]
# auxDirectory = "build"

# [language.config.texlab.chktex]
# onOpenAndSave = true
# onEdit = true

# [language.config.texlab.forwardSearch]
# executable = "zathura"
# args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

# executable = "okular"
# args = ["--unique", "file:%p#src:%l%f"]

# [language.config.texlab.build]
# forwardSearchAfter = true
# onSave = true

# executable = "latexmk"
# args = [
#  "-pdf",
#  "-interaction=nonstopmode",
#  "-synctex=1",
#  "-shell-escape",
#  "-output-directory=build",
#  "%f"
#  ]

# executable = "tectonic"
# args = [
#  "-X",
#  "compile",
#  "%f",
#  "--synctex",
#  "--keep-logs",
#  "--keep-intermediates",
#  "--outdir=build",
#  "-Zshell-escape",
# ]
# [[language]]
# name = "latex"
# scope = "source.tex"
# injection-regex = "latex"
# roots = ["pdf"]
# file-types = ["tex"]
# comment-token = "%"
# indent = { tab-width = 4, unit = "    " }
# formatter = { command = "latexindent", args = ["-i", "4", "-w", "120", "${file}", "-o", "${file}"] }
# auto-format = true

# [[language]]
# name = "latex"

# [language.config.build]
# executable = "latexmk"
# args = ["-pdf", "-interaction=nonstopmode", "-synctex=1", "%f"]
# indent = { tab-width = 4, unit = "    " }
# onSave = true

# [language.config.chktex]
# onOpenAndSave = true
# onEdit = true
# indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
roots = ["pyproject.toml"]
indent = { tab-width = 4, unit = "    " }
comment-token = "#"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true
language-servers = ["ruff", "pylsp", "pyright"]

[language-server.ruff]
command = "ruff-lsp"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pylsp]
command = "pylsp"

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = {enabled = false}

[language-server.tls]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.deno]
command = "deno"
args = ["lsp"]

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json", "--line-width", "120", "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }
language-servers = ["deno", "tls"]

[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js", "--line-width", "120", "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true
language-servers = ["deno", "tls"]


[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts", "--line-width", "120", "--indent-width", "4"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true
language-servers = ["deno", "tls"]
